/**
 * Created by Abhijith on 15-Jul-17.
 * Highly divisible triangular number
 * Problem 12
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * <p>
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * <p>
 * Let us list the factors of the first seven triangle numbers:
 * <p>
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * <p>
 * What is the value of the first triangle number to have over five hundred divisors?
 */

import java.util.*;

public class highlyDivisibleTriangular {
    public static void main(String[] args) {
        calculateDivisor();

    }

    public static void calculateDivisor() {
       long k =1;
       boolean b = true;

       while ( b ){
           long nthTriangle = k *(k +1)/2;
           int numOfDivisor =1;
           for(long i = 1; i <= nthTriangle/2 ;i++)
           {
               if(nthTriangle % i == 0){
                   numOfDivisor ++;
               }
           }
           if(numOfDivisor >= 350){
               System.out.println(nthTriangle);
               b = false;
           }
           k++;
        }

System.out.println("no divisor");
    }
}