/**
 * Created by abhijith on 06-Jun-17.
 * Even Fibonacci numbers
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Fib {
    public static void main(String[] args) {
        long limit = 50;
        long sum = 0;
        long f1 = 0;
        long f2 = 1;
        for (long i = 1; i <= limit; i++) {
            f1 = f1 + f2;
            f2 = f1 - f2;
            //  System.out.println(f1);
            if (f1 % 2 == 0 && f1 < 4000000) {
                sum += f1;
            }


        }
        System.out.println("Sum of even fibonacci series is " + sum);

    }
}

